enableFishingHookCheck: true
enableFrostwalkerCheck: true
enableChorusFruitCheck: true
enableBoatCheck: true
enableEndCrystalCheck: true
enableLilypadCheck: true
#All the checks will be disabled in following worlds
disableAllInWorld:
- put_world_name_here
- or_here
